import test from 'node:test';
import assert from 'node:assert/strict';
import {counts,decisionStatus,emptyState,newDecision,now,stateSchema,uid,weekKey} from '../lib/model.ts';
const p={id:uid(),version:1,market:'NQ / MNQ',mode:'simulation',entry:'Regla de entrada',risk:'Regla de riesgo',limit:'Límite',focus:'Proceso',createdAt:now()};
const d=(statuses=['yes','yes','yes'],type='trade',result='loss')=>({...newDecision(),time:'10:15',fact:'DEMO DATA · Decisión de prueba',type,result,checks:Object.fromEntries(['entry','risk','limit'].map((k,i)=>[k,{status:statuses[i],reason:'Evidencia de prueba'}]))});
const episode=(overrides={})=>({id:uid(),planId:p.id,date:'2026-09-28',session:'DEMO DATA · Caso',source:'simulation',loss:'yes',lossTime:'10:00',lossNote:'Primera pérdida cerrada',coverage:'complete',decisions:[d()],context:'',reflection:'Revisión de prueba',reviewed:true,createdAt:now(),updatedAt:now(),...overrides});
const state=e=>({...emptyState(),consentAt:now(),plans:[p],episodes:[e]});
test('una pérdida conforme no es indisciplina',()=>{assert.equal(decisionStatus(d()),'yes');assert.equal(counts([episode()]).off,0);});
test('una ganancia con varias infracciones cuenta una vez',()=>{const e=episode({decisions:[d(['no','no','yes'],'trade','gain')]});assert.equal(counts([e]).off,1);assert.equal(counts([e]).evaluable,1);});
test('sin decisiones evaluables la proporción no es calculable',()=>assert.equal(counts([episode({decisions:[d(['unknown','yes','yes'])]})]).ratio,null));
test('ausencia de pérdida y cobertura parcial se excluyen',()=>{const c=counts([episode({loss:'no'}),episode({coverage:'partial'}),episode({reviewed:false})]);assert.equal(c.evaluable,0);assert.equal(c.excluded,3);});
test('pausas se conservan y se cuentan aparte',()=>{const c=counts([episode({decisions:[d(['na','yes','yes'],'pause','na')]})]);assert.equal(c.nonTrading,1);assert.equal(c.ratio,null);});
test('clasificación toda no aplica no inventa cumplimiento',()=>assert.equal(decisionStatus(d(['na','na','na'])),'unknown'));
test('una infracción identificada no se oculta por otra regla desconocida',()=>assert.equal(decisionStatus(d(['no','unknown','yes'])),'no'));
test('rechaza decisiones anteriores a la pérdida',()=>{const e=episode();e.decisions[0].time='09:59';assert.equal(stateSchema.safeParse(state(e)).success,false);});
test('rechaza fechas inexistentes',()=>assert.equal(stateSchema.safeParse(state(episode({date:'2026-02-31'}))).success,false));
test('rechaza clasificación sin motivo',()=>{const e=episode();e.decisions[0].checks.entry.reason='';assert.equal(stateSchema.safeParse(state(e)).success,false);});
test('rechaza práctica sin evidencia de origen',()=>{const s=state(episode());s.practices=[{id:uid(),episodeId:uid(),rule:'entry',action:'Acción',when:'Condición',active:true,createdAt:now(),reports:[]}];assert.equal(stateSchema.safeParse(s).success,false);});
test('conserva práctica al corregir su origen, pendiente de revisión',()=>{const e=episode({reviewed:false});const s=state(e);s.practices=[{id:uid(),episodeId:e.id,rule:'entry',action:'Acción',when:'Condición',active:true,createdAt:now(),reports:[]}];assert.equal(stateSchema.safeParse(s).success,true);});
test('rechaza usar dos veces una oportunidad',()=>{const e=episode();const later=episode({date:'2026-09-29'});const s=state(e);s.episodes.push(later);s.practices=[{id:uid(),episodeId:e.id,rule:'entry',action:'Acción',when:'Condición',active:true,createdAt:now(),reports:[1,2].map(()=>({id:uid(),date:later.date,episodeId:later.id,result:'applied',note:'Evidencia'}))}];assert.equal(stateSchema.safeParse(s).success,false);});
test('una semana comienza el lunes y cruza meses correctamente',()=>{assert.equal(weekKey('2026-03-01'),'2026-02-23');assert.equal(weekKey('2026-09-29'),'2026-09-28');});
test('nueva referencia mantiene la validez histórica de cada caso',()=>{const e=episode();const s=state(e);s.plans.push({...p,id:uid(),version:2,mode:'own'});assert.equal(stateSchema.safeParse(s).success,true);assert.equal(s.episodes[0].planId,p.id);});
